version: '3.4'

services:
  one-api:
    image: "${REGISTRY:-docker.io}/magic/fm-management-app:latest"
    container_name: fm-management-app
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data/fm-management-app:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=fm-management-app:123456@tcp(db:3306)/fm-management-app  
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string  
      - TZ=America/New_York
    depends_on:
      - redis
      - db
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: "${REGISTRY:-docker.io}/redis:latest"
    container_name: redis
    restart: always

  db:
    image: "mysql:8.2.0"
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql  # persistent storage
    ports:
      - '3306:3306'
    environment:
      TZ: America/New_York   
      MYSQL_ROOT_PASSWORD: 'magic@wizard' 
      MYSQL_USER: wizard   
      MYSQL_PASSWORD: 'magic'    
      MYSQL_DATABASE: magic  
